### ISSUE TITLE
Doesn't work with nuxt

### ISSUE THREAD

**Issue by andrey-helldar** [WildCodeSchool/vue-calendar-heatmap#16]
![image](https://user-images.githubusercontent.com/10347617/104706989-de055100-572c-11eb-9fb0-26f2b9d11409.png)

**Comment by kiddten** [comment]
try to turn of ssr like this `{ src: '~/plugins/vue-calendar-heatmap', ssr: false }`

**Comment by andrey-helldar** [comment]
> try to turn of ssr like this `{ src: '~/plugins/vue-calendar-heatmap', ssr: false }`

I am using nuxt for ssr only.
