### ISSUE TITLE
Missing required prop: "endDate"

### ISSUE THREAD

**Issue by markuman** [WildCodeSchool/vue-calendar-heatmap#5]
Vuejs 2.5.17 on Firefox & Chromium

### minimal example
```html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8"> 
<head>
  <title>Welcome to my Heatmap</title>
  <script src="./vue.js"></script>
  <link rel="stylesheet" href="./vue-calendar-heatmap.css"/>
  <script src="./vue-calendar-heatmap.browser.js"></script>
</head>
<body>
  <div id="app">
    <calendar-heatmap :endDate="today" :values="values"/>
  </div>
  <script>
      
    new Vue({
      el: '#app',
      components: {
        VueCalendarHeatmap
      },
      data: {
        today: new Date(),
        values: [{ date: '2018-09-22', count: 6 }]
      },
    });
    
  </script>
</body>
</html>
```

It doesn't matter how I pass `endDate` through the component. `:endDate="2018-09-11"` or `endDate="2018-09-11"` also failed with the same message.

However, when I change the `endDate` property like this

```diff
diff --git a/src/components/CalendarHeatmap.vue b/src/components/CalendarHeatmap.vue
index 18cde00..5460d4e 100644
--- a/src/components/CalendarHeatmap.vue
+++ b/src/components/CalendarHeatmap.vue
@@ -72,7 +72,7 @@ export default {

   props: {
     endDate: {
-      required: true
+      default: new Date()
     },
     max: {
       type: Number
```

and re-run `npm run build:browser`, I receive another error message

`[Vue warn]: Invalid default value for prop "endDate": Props with type Object/Array must use a factory function to return the default value.`

But vue dev tools shows that `endDate` is a correct date object.

![enddate](https://user-images.githubusercontent.com/3920157/45367958-acbb6a00-b5e2-11e8-9e2e-e4b7b312e585.png)

So I've absolutely now idea how to use this component correctly. Any hints?

**Comment by markuman** [comment]
I get it to work with this change

```diff
diff --git a/src/components/CalendarHeatmap.vue b/src/components/CalendarHeatmap.vue
index 18cde00..d203a2c 100644
--- a/src/components/CalendarHeatmap.vue
+++ b/src/components/CalendarHeatmap.vue
@@ -72,7 +72,7 @@ export default {

   props: {
     endDate: {
-      required: true
+      default: () => new Date()
     },
     max: {
       type: Number
```

but no chance to pass this as a property ...

**Comment by julienr114** [comment]
I think you should rather write the `enDate` props in this way:
```html
<calendar-heatmap :end-date="today" :values="values"/>
```
 To my knowledge we can not write the html attribute with capital letters

**Comment by julienr114** [comment]
fixe in #6
